repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # MyPy - Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy

  # Built-in pre-commit hooks for general file health
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Remove trailing whitespace
      - id: trailing-whitespace
      # Ensure files end with newline
      - id: end-of-file-fixer
      # Check for merge conflicts
      - id: check-merge-conflict
      # Check YAML syntax
      - id: check-yaml
      # Check TOML syntax
      - id: check-toml
      # Check JSON syntax
      - id: check-json
      # Prevent large files from being committed
      - id: check-added-large-files
        args: ['--maxkb=1000']
      # Check for case conflicts
      - id: check-case-conflict
      # Check for executable permissions on non-executable files
      - id: check-executables-have-shebangs
      # Fix line endings
      - id: mixed-line-ending
        args: ['--fix=lf']
